eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
      instance:
      preferIpAddress: true
server:
  port: 8763
  servlet:
    context-path: /uaa

spring:
  application:
      name: auth-service
  datasource: 
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/securityTestDB
    username: postgres
    password: admin
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace